language: python
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
   - psql -c 'create database fastfoodfasttest;' -U postgres

script:
  - nosetests -v --with-coverage --cover-package=app

after_success:
- coveralls
