language: python
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
   - psql -c 'create database fastfoodfast;' -U postgres

script:
  - pytest --cov-config .coveragerc --cov=app tests/
  - coverage report

after_success:
- coveralls
- pytest
