language: python
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt
<<<<<<< HEAD

services:
  - postgresql

before_script:
   - psql -c 'create database fastfoodfast;' -U postgres

script:
  - nosetests -v --with-coverage --cover-package=app

after_success:
- coveralls
=======
  - pip install coverage
  - pip install coveralls
  - pip install nose
  
# command to run tests
script:
  - nosetests -v --with-coverage --cover-package=api

after_success:
- coveralls
>>>>>>> fd785df93e7e94d95f11562329ab42e870685ac1
